### ISSUE TITLE
Moon icon is too thick on light background and fuzzy on dark background

### ISSUE THREAD

**Issue by ecircenis** [grommet/grommet-icons#180] opened 2020-05-26 16:17 UTC
The new moon icon has too thick a stroke on a light background and shows up fuzzy on a dark background:
![image](https://user-images.githubusercontent.com/17883783/82924812-21127a00-9f3a-11ea-861e-cee71fe9916a.png)

**Comment by ShimiSun** [comment] 2020-06-01 20:45
@L0ZZI and @saggiemilva let's resolve this issue before continuing to add more icons from Figma.

**Comment by ShimiSun** [comment] 2020-06-01 22:16
Investigating this issue with the designers and the dev side, and it looks like we are applying the color properly 
![image](https://user-images.githubusercontent.com/6320236/83460247-2cc2dc80-a423-11ea-9493-1995ceb1a8c1.png)

I think the issue might be coming from designer itself? @ericsoderberghp

**Comment by ericsoderberghp** [comment] 2020-06-03 14:22
I think the issue is that the moon is a filled path whereas the other icons are stroked paths. For example, the Actions icon has `fill="none" stroke="#000" stroke-width="2"` for its path but the Moon icon has `fill="black"` for its path. I think the filled approach doesn't handle the scaling up and down of the icon size as well as the stroke approach.

**Comment by ericsoderberghp** [comment] 2020-06-03 14:37
The reason we don't see this visually on icons.grommet.io is because the icons are rendered with `color="plain"`. In the designer, we don't do this and instead let the the color prop be set by the design. Here's an example where the color is set for each of these icons, but the Moon doesn't get the color, due to the `fill`.

![Screen Shot 2020-06-03 at 7 36 29 AM](https://user-images.githubusercontent.com/11637956/83650300-0c069e00-a56d-11ea-898c-17a2e0214ee2.png)

**Comment by saggiemilva** [comment] 2020-06-18 16:49
@ShimiSun I remade the moon icon so it should not have any fill properties. Please let me know if this solves the issue:
[moon.svg.zip](https://github.com/grommet/grommet-icons/files/4799969/moon.svg.zip)

**Comment by ShimiSun** [comment] 2020-07-09 20:02
Fixed on PR #186

**Closed by ShimiSun** 2020-07-09 20:02 UTC
